image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start VNC & Wine
    init: |
      mkdir -p ~/.vnc
      echo "gitpod" | vncpasswd -f > ~/.vnc/passwd
      chmod 600 ~/.vnc/passwd
      export DISPLAY=:1
      vncserver :1 -geometry 1280x720 -depth 24
      wineboot --init
    command: sleep infinity

vscode:
  extensions:
    - ms-vscode.remote-explorer
